<?php
/**
 * Auto-generated by RockyJam Hook Manager. Do not edit manually.
 * Edit via: Templates → rogue-product → Hooks
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

// Hook: woocommerce_before_single_product_summary
remove_action( 'woocommerce_before_single_product_summary', 'woocommerce_show_product_sale_flash', 10 );
add_action( 'woocommerce_before_single_product_summary', 'woocommerce_show_product_sale_flash', 10 );
remove_action( 'woocommerce_before_single_product_summary', 'woocommerce_show_product_images', 20 );
add_action( 'woocommerce_before_single_product_summary', 'woocommerce_show_product_images', 20 );

// Hook: woocommerce_single_product_summary
remove_action( 'woocommerce_single_product_summary', 'rockyjam_shipping_badge_render', 3 );
if ( function_exists( 'rockyjam_shipping_badge_render' ) ) {
	add_action( 'woocommerce_single_product_summary', 'rockyjam_shipping_badge_render', 3 );
}
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_title', 5 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_title', 5 );
// Product Subtitle — addon: product-subtitle, priority 6 (right after title)
remove_action( 'woocommerce_single_product_summary', 'rockyjam_product_subtitle_render', 6 );
if ( function_exists( 'rockyjam_product_subtitle_render' ) ) {
	add_action( 'woocommerce_single_product_summary', 'rockyjam_product_subtitle_render', 6 );
}
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_rating', 10 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_rating', 10 );
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 10 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_price', 10 );

/**
 * Stock availability badge — priority 12 (between price and key-features).
 *
 * WC's get_availability_text() returns '' when manage_stock=false and item is in stock.
 * In that case we fall back to is_in_stock() to still show the badge.
 */
add_action( 'woocommerce_single_product_summary', function() {
	global $product;
	if ( ! $product instanceof WC_Product ) {
		return;
	}

	$availability = $product->get_availability();
	$text         = ! empty( $availability['availability'] ) ? $availability['availability'] : '';
	$class        = ! empty( $availability['class'] ) ? $availability['class'] : '';

	// Fallback: manage_stock=false — WC returns empty text but stock status is set
	if ( '' === $text ) {
		if ( $product->is_in_stock() ) {
			$text  = __( 'In stock', 'woocommerce' );
			$class = 'in-stock';
		} else {
			$text  = __( 'Out of stock', 'woocommerce' );
			$class = 'out-of-stock';
		}
	}

	echo '<p class="stock ' . esc_attr( $class ) . '">' . esc_html( $text ) . '</p>';
}, 12 );

remove_action( 'woocommerce_single_product_summary', 'rockyjam_keyfeatures_render', 15 );
if ( function_exists( 'rockyjam_keyfeatures_render' ) ) {
	add_action( 'woocommerce_single_product_summary', 'rockyjam_keyfeatures_render', 15 );
}
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 20 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_excerpt', 20 );
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_meta', 40 );
remove_action( 'woocommerce_single_product_summary', 'rockyjam_product_badges_render', 45 );
if ( function_exists( 'rockyjam_product_badges_render' ) ) {
	add_action( 'woocommerce_single_product_summary', 'rockyjam_product_badges_render', 45 );
}

// TEST: completely disable the default Add to Cart button for rogue-product
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 50 );

remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_sharing', 50 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_sharing', 60 );

// Hook: woocommerce_after_single_product_summary
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_product_data_tabs', 10 );
add_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_product_data_tabs', 10 );
remove_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_benefits_render', 18 );
if ( function_exists( 'rockyjam_product_benefits_render' ) ) {
	add_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_benefits_render', 18 );
}
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );
remove_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_faq_render', 25 );
if ( function_exists( 'rockyjam_product_faq_render' ) ) {
	add_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_faq_render', 25 );
}
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );
add_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 30 );

// Hook: woocommerce_product_thumbnails
remove_action( 'woocommerce_product_thumbnails', 'woocommerce_show_product_thumbnails', 20 );
add_action( 'woocommerce_product_thumbnails', 'woocommerce_show_product_thumbnails', 20 );
