<?php
/**
 * Rogue Product Template — hooks.php
 * AUTO-GENERATED by RockyJam Templates. Do not edit manually.
 *
 * Hook order in woocommerce_single_product_summary:
 *   3  - rockyjam_shipping_badge_render   (Shipping Badge addon)
 *   5  - woocommerce_template_single_title
 *  10  - woocommerce_template_single_rating
 *  10  - woocommerce_template_single_price
 *  15  - rockyjam_keyfeatures_render       (Key Features addon)
 *  20  - woocommerce_template_single_excerpt
 *  40  - woocommerce_template_single_meta
 *  45  - rockyjam_product_badges_render    (Product Badges addon)
 *  50  - woocommerce_template_single_add_to_cart  (moved from 30)
 *  60  - woocommerce_template_single_sharing      (moved from 50)
 *
 * Hook order in woocommerce_after_single_product_summary:
 *  10  - woocommerce_output_product_data_tabs
 *  18  - rockyjam_product_benefits_render  (Product Benefits addon)
 *  25  - rockyjam_product_faq_render       (Product FAQ addon)
 *  30  - woocommerce_output_related_products (moved from 20)
 */

defined( 'ABSPATH' ) || exit;

// ---- woocommerce_before_single_product_summary ----
// Sale flash: enabled at original priority (no change needed)
// Product images: enabled at original priority (no change needed)

// ---- woocommerce_single_product_summary ----

// Shipping Badge addon (priority 3)
if ( function_exists( 'rockyjam_shipping_badge_render' ) ) {
    add_action( 'woocommerce_single_product_summary', 'rockyjam_shipping_badge_render', 3 );
}

// Product Title (priority 5) — default is 5, no change needed

// Rating (priority 10) — default, no change needed

// Price (priority 10) — default, no change needed

// Key Features addon (priority 15)
if ( function_exists( 'rockyjam_keyfeatures_render' ) ) {
    add_action( 'woocommerce_single_product_summary', 'rockyjam_keyfeatures_render', 15 );
}

// Short Description (priority 20) — default, no change needed

// Meta (priority 40) — default, no change needed

// Product Badges addon (priority 45)
if ( function_exists( 'rockyjam_product_badges_render' ) ) {
    add_action( 'woocommerce_single_product_summary', 'rockyjam_product_badges_render', 45 );
}

// Add to Cart: move from default 30 → 50
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 30 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_add_to_cart', 50 );

// Social Sharing: move from default 50 → 60
remove_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_sharing', 50 );
add_action( 'woocommerce_single_product_summary', 'woocommerce_template_single_sharing', 60 );

// Remove upsell from summary (not in sidebar)
remove_action( 'woocommerce_single_product_summary', 'wc_upsell_display', 15 );

// ---- woocommerce_after_single_product_summary ----

// Product Tabs (priority 10) — default, no change needed

// Product Benefits addon (priority 18)
if ( function_exists( 'rockyjam_product_benefits_render' ) ) {
    add_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_benefits_render', 18 );
}

// Upsell: disable (not needed in this template)
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );

// Product FAQ addon (priority 25)
if ( function_exists( 'rockyjam_product_faq_render' ) ) {
    add_action( 'woocommerce_after_single_product_summary', 'rockyjam_product_faq_render', 25 );
}

// Related Products: move from default 20 → 30
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 20 );
add_action( 'woocommerce_after_single_product_summary', 'woocommerce_output_related_products', 30 );
