<?php

namespace RockyJamTemplates\Core;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Reads and writes hooks-config.json for a single template,
 * and regenerates hooks.php from that config.
 *
 * Config structure (hooks-config.json):
 * [
 *   {
 *     "hook": "woocommerce_single_product_summary",
 *     "callbacks": [
 *       {
 *         "id":       "woocommerce_template_single_title",
 *         "function": "woocommerce_template_single_title",
 *         "priority": 5,
 *         "enabled":  true,
 *         "custom":   false,
 *         "label":    "Product Title",
 *         "code":     ""       // only for custom callbacks
 *       },
 *       ...
 *     ]
 *   },
 *   ...
 * ]
 *
 * @package RockyJamTemplates
 */
class HooksConfig {

	private string $template_dir;
	private string $config_path;
	private string $hooks_php_path;

	public function __construct( string $slug ) {
		$this->template_dir   = TemplateManager::templates_dir() . $slug . '/';
		$this->config_path    = $this->template_dir . 'hooks-config.json';
		$this->hooks_php_path = $this->template_dir . 'hooks.php';
	}

	// ------------------------------------------------------------------
	// Registry helpers
	// ------------------------------------------------------------------

	/**
	 * Returns the path to the WC hooks registry JSON file.
	 */
	public static function registry_path(): string {
		return RJT_PATH . 'data/wc-hooks-registry.json';
	}

	/**
	 * Loads the WC hooks registry.
	 *
	 * @return array[] List of hook definitions.
	 */
	public static function load_registry(): array {
		$path = self::registry_path();
		if ( ! file_exists( $path ) ) {
			return [];
		}
		$json = file_get_contents( $path );
		$data = json_decode( $json, true );
		return is_array( $data['hooks'] ?? null ) ? $data['hooks'] : [];
	}

	// ------------------------------------------------------------------
	// Read
	// ------------------------------------------------------------------

	/**
	 * Reads hooks-config.json for this template.
	 * If it doesn't exist, returns the default config built from the registry.
	 *
	 * @return array[]
	 */
	public function read(): array {
		if ( file_exists( $this->config_path ) ) {
			$json = file_get_contents( $this->config_path );
			$data = json_decode( $json, true );
			if ( is_array( $data ) ) {
				return $data;
			}
		}
		return $this->build_default_config();
	}

	/**
	 * Builds the initial config from the registry (all standard hooks / callbacks).
	 *
	 * @return array[]
	 */
	private function build_default_config(): array {
		$registry = self::load_registry();
		$config   = [];
		foreach ( $registry as $hook_def ) {
			$entry = [
				'hook'      => $hook_def['hook'],
				'callbacks' => [],
			];
			foreach ( $hook_def['callbacks'] ?? [] as $cb ) {
				$entry['callbacks'][] = [
					'id'       => $cb['id'],
					'function' => $cb['function'],
					'priority' => (int) $cb['priority'],
					'enabled'  => (bool) $cb['enabled'],
					'custom'   => false,
					'label'    => $cb['label'] ?? $cb['function'],
					'code'     => '',
				];
			}
			$config[] = $entry;
		}
		return $config;
	}

	// ------------------------------------------------------------------
	// Write
	// ------------------------------------------------------------------

	/**
	 * Saves a config array to hooks-config.json.
	 *
	 * @param array[] $config
	 * @return true|\WP_Error
	 */
	public function save( array $config ) {
		$config = $this->sanitize_config( $config );
		$json   = wp_json_encode( $config, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE );

		if ( false === file_put_contents( $this->config_path, $json ) ) {
			return new \WP_Error( 'write_error', __( 'Could not write hooks-config.json. Check permissions.', 'rockyjam-templates' ) );
		}

		return $this->regenerate_hooks_php( $config );
	}

	// ------------------------------------------------------------------
	// PHP generation
	// ------------------------------------------------------------------

	/**
	 * Regenerates hooks.php from the given config.
	 *
	 * @param array[] $config
	 * @return true|\WP_Error
	 */
	public function regenerate_hooks_php( array $config ): bool|\WP_Error {
		$lines   = [];
		$lines[] = '<?php';
		$lines[] = '/**';
		$lines[] = ' * Auto-generated by RockyJam Hook Manager. Do not edit manually.';
		$lines[] = ' * Edit via: Templates → [template] → Hooks';
		$lines[] = ' */';
		$lines[] = '';
		$lines[] = 'if ( ! defined( \'ABSPATH\' ) ) { exit; }';
		$lines[] = '';

		foreach ( $config as $hook_entry ) {
			$hook = $hook_entry['hook'] ?? '';
			if ( ! $hook ) {
				continue;
			}

			$callbacks = $hook_entry['callbacks'] ?? [];
			if ( empty( $callbacks ) ) {
				continue;
			}

			$lines[] = '// Hook: ' . $hook;

			foreach ( $callbacks as $cb ) {
				$priority = (int) ( $cb['priority'] ?? 10 );
				$enabled  = (bool) ( $cb['enabled']  ?? true );
				$custom   = (bool) ( $cb['custom']   ?? false );
				$func     = $cb['function'] ?? '';
				$code     = $cb['code']     ?? '';
				$id       = $cb['id']       ?? '';

				if ( $custom ) {
					// ── Custom inline function ───────────────────────────────────
					if ( ! $enabled || ! $func || ! $code ) {
						continue;
					}
					// Wrap body in a proper named function declaration.
					$safe_code = $this->indent_code( trim( $code ) );
					$lines[]   = 'if ( ! function_exists( \'' . $func . '\' ) ) {';
					$lines[]   = "\tfunction " . $func . '() {';
					$lines[]   = $safe_code;
					$lines[]   = "\t}";
					$lines[]   = '}';
					$lines[]   = 'add_action( \'' . $hook . '\', \'' . $func . '\', ' . $priority . ' );';
				} else {
					// ── Standard WC callback ─────────────────────────────────────
					// Strategy: always remove_action first (safe even if not registered),
					// then re-add only if enabled. This correctly handles:
					//   disabled          → remove only  (turns WC default off)
					//   enabled, same p   → remove + re-add at same priority (net: no change, but correct)
					//   enabled, new p    → remove old + add at new priority
					if ( ! $func ) {
						continue;
					}
					// Remove whatever WC registered at this priority.
					$lines[] = 'remove_action( \'' . $hook . '\', \'' . $func . '\', ' . $priority . ' );';
					if ( $enabled ) {
						// Re-register at the (possibly changed) priority.
						$lines[] = 'add_action( \'' . $hook . '\', \'' . $func . '\', ' . $priority . ' );';
					}
				}
			}

			$lines[] = '';
		}

		$php = implode( "\n", $lines );

		if ( false === file_put_contents( $this->hooks_php_path, $php ) ) {
			return new \WP_Error( 'write_error', __( 'Could not write hooks.php. Check permissions.', 'rockyjam-templates' ) );
		}

		return true;
	}

	// ------------------------------------------------------------------
	// Sanitization
	// ------------------------------------------------------------------

	/**
	 * Sanitizes a config array received from the browser.
	 *
	 * @param array[] $config
	 * @return array[]
	 */
	private function sanitize_config( array $config ): array {
		$clean = [];

		foreach ( $config as $hook_entry ) {
			if ( ! is_array( $hook_entry ) ) {
				continue;
			}
			$hook = sanitize_key( $hook_entry['hook'] ?? '' );
			if ( ! $hook ) {
				continue;
			}

			$entry = [
				'hook'      => $hook,
				'callbacks' => [],
			];

			foreach ( $hook_entry['callbacks'] ?? [] as $cb ) {
				if ( ! is_array( $cb ) ) {
					continue;
				}
				$custom   = (bool) ( $cb['custom']   ?? false );
				$func     = sanitize_key( $cb['function'] ?? '' );
				$priority = max( 1, min( 999, (int) ( $cb['priority'] ?? 10 ) ) );
				$enabled  = (bool) ( $cb['enabled']  ?? true );
				$label    = sanitize_text_field( $cb['label'] ?? $func );
				$id       = sanitize_key( $cb['id'] ?? $func );
				// Raw PHP code — keep as-is (admin-only, manage_options required).
				$code = $cb['code'] ?? '';

				if ( ! $func ) {
					continue;
				}

				$entry['callbacks'][] = [
					'id'       => $id,
					'function' => $func,
					'priority' => $priority,
					'enabled'  => $enabled,
					'custom'   => $custom,
					'label'    => $label,
					'code'     => $code,
				];
			}

			$clean[] = $entry;
		}

		return $clean;
	}

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	/**
	 * Indents code lines by one tab (for function body).
	 */
	private function indent_code( string $code ): string {
		$lines = explode( "\n", $code );
		return implode( "\n", array_map( fn( $l ) => "\t" . $l, $lines ) );
	}
}
